name: CI
on: [push]
jobs:
  build:
    name: ${{ matrix.node-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install dependencies"
        run: npm ci
      - run: npm run test
